### ISSUE TITLE
Woocommerce 

### ISSUE THREAD

**Issue by campaigncenter** [Bankart-PGW/bankart-woocommerce#1]
PHP version: 8.0 and tried 8.1
Plugin WooCommerce Bankart Payment Gateway Extension version 1.7.4.3
Woocommerce Version 8.1.1 
Woocommerce -> Settings -> Payments -> Payment cards – Plačilna kartica enabled and fully setup

On Woocommerce Checkout it reports that there is no payment method:
<img width="1436" alt="Screenshot 2023-10-06 at 13 40 03" src="https://github.com/Bankart-PGW/bankart-woocommerce/assets/73285201/056b4890-9a6b-4489-afd9-24833a8d5fcc">
<img width="1292" alt="Screenshot 2023-10-06 at 13 49 19" src="https://github.com/Bankart-PGW/bankart-woocommerce/assets/73285201/50c36b24-61cd-4858-864e-543c5abc7a44">

**Comment by Bankart-PGW** [comment]
This is because plugin not support cart/checkout blocks. For reverting to the cart and checkout shortcodes please referer to https://woo.com/document/cart-checkout-blocks-status/#section-6

**Comment by Bankart-PGW** [comment]
In new version 3.1.1.1 issue is resolved
